### PR TITLE
Add 2016UL Rochester corrections.

### LINKED ISSUE #18: Implementation for Rochester Corrections for UL18 and UL16 is missing
Currently there are no Rochester Corrections provided by CMS in the official [TWiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/RochcorMuon). As soon as they are available the Rochester Corrections should also be applied for UL18 and UL16 datasets in a similar fashion to #15.

### PR DESCRIPTION
**Pull request by rfvc**
This adds the Rochester corrections for ultra legacy 2016 from version Run2.v5

### CODE REVIEW

**Review by HerrHorizontal — CHANGES_REQUESTED** [review]
Since you have been doing the work for UL16. Would you also add the UL18 files and include the necessary line in the Producers?

**Comment by rfvc** [comment]
I just added the correction files in v5 for UL17 and UL18. The producer should be fine already.

**Comment by rfvc** [comment]
I just added the rochester correction files in v5 for UL17 and UL18 and adapted the producer.

**Review by HerrHorizontal — APPROVED** [review]
Looks good now. :+1:
Many thanks for your efforts.

**Comment by HerrHorizontal** [comment]
Closes #18

**Pull request merged**
