### PR TITLE
Update/rocco r

### LINKED ISSUE #14: Run 2 Rochester Corrections with UL
Run 2 Rochester Corrections for UL campaign https://twiki.cern.ch/twiki/pub/CMS/RochcorMuon/roccor.Run2.v4.tgz need to be added into the code [/Utility/interface/RoccoR.h](https://github.com/KIT-CMS/Artus/blob/72645ccfe5217ecc01488d711be8a879327e528d/Utility/interface/RoccoR.h) and [/Utility/src/RoccoR.cc](https://github.com/KIT-CMS/Artus/blob/72645ccfe5217ecc01488d711be8a879327e528d/Utility/src/RoccoR.cc).

Furthermore, it is not necessary anymore to differentiate the treatment of 2016 Rochester Corrections. 

Also, there might be some changes in the recommended methods to compute the `scaleFactors`, since the methods 
```C++
//old, should only be used with 2017v0
double kScaleFromGenMC(int Q, double pt, double eta, double phi, int n, double gt, double w, int s=0, int m=0) const; 
double kScaleAndSmearMC(int Q, double pt, double eta, double phi, int n, double u, double w, int s=0, int m=0) const;  
double kScaleFromGenMCerror(int Q, double pt, double eta, double phi, int n, double gt, double w) const; 
double kScaleAndSmearMCerror(int Q, double pt, double eta, double phi, int n, double u, double w) const;  
```
provided are deprecated and still in use in [/KappaAnalysis/src/Producers/MuonCorrectionsProducer.cc](https://github.com/KIT-CMS/Artus/blob/72645ccfe5217ecc01488d711be8a879327e528d/KappaAnalysis/src/Producers/MuonCorrectionsProducer.cc).

### PR DESCRIPTION
**Pull request by HerrHorizontal**
Changed the behaviour for Rochester Corrections for 2016 data and MC from seperate to newer recommended default treatment. Also included RoccoR for 2017UL.

### CODE REVIEW

**Comment by HerrHorizontal** [comment]
The official recommendations for Rochester Corrections can be found at https://twiki.cern.ch/twiki/bin/viewauth/CMS/RochcorMuon.

For configuration you have to add:
```python
cfg['MuonRochesterCorrectionsFile'] = os.path.join(configtools.getPath(),'../Artus/KappaAnalysis/data/[FilePath]')
cfg['MuonEnergyCorrection'] = 'RoccoR2016'
```
to your config file pointing to the according textfile `RoccoR[year][, UL].txt` and the according energy correction `'RoccoR[year][, UL]'`.

**Review by mschnepf — APPROVED** [review]
Thanks for your work :+1:

**Comment by HerrHorizontal** [comment]
There has been a mistake in the treatment of checking the version of Rochester Correction in `MuonCorrectionsProducer::ToMuonEnergyCorrection()`.

**Review by mschnepf — COMMENTED** [review]
I'm wondering a bit.
You defined in 19485976644fc34b98786913155a619e15b82207 the enum for 2016UL and  2018U. However, these can not be chosen by `MuonCorrectionsProducer::ToMuonEnergyCorrection()`
Please add at least the option for `2016UL`.

**Comment by HerrHorizontal** [comment]
> I'm wondering a bit.
> You defined in [1948597](https://github.com/KIT-CMS/Artus/commit/19485976644fc34b98786913155a619e15b82207) the enum for 2016UL and 2018U. However, these can not be chosen by `MuonCorrectionsProducer::ToMuonEnergyCorrection()`
> Please add at least the option for `2016UL`.

Done

**Comment by mschnepf** [comment]
Thanks, looks good now. If you have tested it, you can merge it. :-)

**Comment by HerrHorizontal** [comment]
@mschnepf @rfvc Since there are no Rochester Corrections for UL18 and UL16 available yet, I suggest to merge this branch and create an issue for a future implementation of these.

**Pull request merged**
